<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-11-18 14:02

$extensionPath = t3lib_extMgm::extPath('ics_od_datastore');
return array(
	'tx_icsoddatastore_filecontrol' => $extensionPath . 'lib/class.tx_icsoddatastore_filecontrol.php',
	'tx_icsoddatastore_filemanager' => $extensionPath . 'lib/class.tx_icsoddatastore_filemanager.php',
	'tx_icsoddatastore_recordlist' => $extensionPath . 'lib/class.tx_icsoddatastore_recordlist.php',
	'tx_icsoddatastore_sysfolder' => $extensionPath . 'lib/class.tx_icsoddatastore_sysfolder.php',
	'tx_icsoddatastore_module1' => $extensionPath . 'mod1/index.php',
	'tx_icsoddatastore_navframe' => $extensionPath . 'mod1/tx_icsoddatastore_navframe.php',
	'tx_icsoddatastore_pi1' => $extensionPath . 'pi1/class.tx_icsoddatastore_pi1.php',
	'tx_icsoddatastore_pi1_wizicon' => $extensionPath . 'pi1/class.tx_icsoddatastore_pi1_wizicon.php',
);
?>