<?php
class tx_smileicsoddatastorelicense_applicationFieldsRenderControls{

	function applicationFieldsValidate(&$errors, &$application, &$conf, &$pObj){
		$this->pObj = $pObj;
		$GP = t3lib_div::_GP($this->pObj->prefixId) ;
		if(isset($GP['cgu'])){
			$this->storeSessionValues('user', 'cgu_accepted', $GP['cgu']);
		}
	}

	/**
	 * [Describe function...]
	 *
	 * @param	[type]		$$keyuid: ...
	 * @param	[type]		$data: ...
	 * @param	[type]		$fields: ...
	 * @param	[type]		$conf: ...
	 * @param	[type]		$pObj: ...
	 * @return	[type]		...
	 */
	function applicationFieldsDBUpdate(&$keyuid, &$data, &$fields, &$conf, &$pObj){

	}

	/**
	 * [Describe function...]
	 *
	 * @param	[type]		$$keyuid: ...
	 * @param	[type]		$data: ...
	 * @param	[type]		$fields: ...
	 * @param	[type]		$conf: ...
	 * @param	[type]		$pObj: ...
	 * @return	[type]		...
	 */
	function applicationFieldsDBUpdateAfter(&$keyuid, &$data, &$fields, &$conf, &$pObj){

	}

	/**
	 * [Describe function...]
	 *
	 * @param	[type]		$$markers: ...
	 * @param	[type]		$subpartArray: ...
	 * @param	[type]		$subpart: ...
	 * @param	[type]		$application: ...
	 * @param	[type]		$conf: ...
	 * @param	[type]		$pObj: ...
	 * @return	[type]		...
	 */
	function applicationFieldsRenderData(&$markers, &$subpartArray, &$subpart, &$application, &$conf, &$pObj){

	}

	/**
	 * [Describe function...]
	 *
	 * @param	[type]		$type: ...
	 * @param	[type]		$var: ...
	 * @param	[type]		$content: ...
	 * @return	[type]		...
	 */
	function storeSessionValues($type, $var, $content) {
		$GLOBALS['TSFE']->fe_user->setKey($type, $var, $content);
		$GLOBALS['TSFE']->storeSessionData();
	}

}
?>